port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7893
mixed-port: 7894
mode: rule
log-level: info
allow-lan: true
unified-delay: true
ipv6: false
bind-address: "*"
external-controller: 0.0.0.0:9090
external-ui: yacd-gh-pages
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: false
  use-host: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - tcp://1.1.1.1
    - tcp://8.8.8.8
  fallback:
    - 1.0.0.1
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
    - 112.215.37.165
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 112.215.37.165
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - +.battlenet.com.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - heartbeat.belkin.com
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - +.nflxvideo.net
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.mcdn.bilivideo.cn"
    - +.media.dssott.com
bug:
  - &tt1 v24.muscdn.com   #WS 443 v2ray/trojan
  - &tt2 v27.tiktokcdn.com  #WS 443 v2ray/trojan
  - &game cf-vod.nimo.tv  #WS CDN 80 v2ray
  - &game1 ir.huya.com  #WS CDN 443 trojan-go
  - &game2 cdn.riseofnowlin.mobi
  - &game3 api.duniagames.co.id #WS CDN 443 Trojan-go
  - &pgame3 104.18.41.141 #WS CDN 443
  - &pgame1 104.18.20.219
  - &pgame2 104.18.3.179
  - &pgame 104.18.12.120
  - &popok 104.17.2.81 #WS CDN 443
  - &opok api.midtrans.com 
  - &sg1 sg1-v2ray.sshkit.org
  - &sg2 sg2-v2ray.sshkit.org
  - &sg3 sg3-v2ray.sshkit.org
  - &sg4 sg4-v2ray.sshkit.org
  - &sg5 sg5-v2ray.sshkit.org
  - &sg6 sg6-v2ray.sshkit.org
proxies:
#Account Telegram i'am hackdeem
#Expired 2022-09-27
  - name: "🇸🇬 Singapore 1 HE"
    type: vmess
    server: *pgame3
    port: 443
    uuid: 7076aa18-20ec-4a66-b792-80d0d69ab74c
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    skip-cert-verify: true
    servername: *game3
    network: ws
    ws-opts:
      path: ws://api.duniagames.co.id/sshkit/5085668734/630b54568be3e/
      headers:
        Host: *sg1
        
  - name: "🇸🇬 Singapore 2 HE"
    type: vmess
    server: *pgame3
    port: 443
    uuid: c6747da4-fb2e-4a2a-bdb7-8614bdd6b0b3
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    skip-cert-verify: true
    servername: *game3
    network: ws
    ws-opts:
      path: ws://api.duniagames.co.id/sshkit/5085668734/630b5493b64f4/
      headers:
        Host: *sg2
        
  - name: "🇸🇬 Singapore 1 CTB"
    type: vmess
    server: *pgame3
    port: 443
    uuid: c6747da4-fb2e-4a2a-bdb7-8614bdd6b0b3
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    skip-cert-verify: true
    servername: *game3
    network: ws
    ws-opts:
      path: ws://api.duniagames.co.id/sshkit/5085668734/630b54ab2db3d/
      headers:
        Host: *sg3
        
  - name: "🇸🇬 Singapore 2 CTB"
    type: vmess
    server: *pgame3
    port: 443
    uuid: c6747da4-fb2e-4a2a-bdb7-8614bdd6b0b3
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    skip-cert-verify: true
    servername: *game3
    network: ws
    ws-opts:
      path: ws://api.duniagames.co.id/sshkit/5085668734/630b54c254072/
      headers:
        Host: *sg4
        
proxy-groups:
  - name: 🇮🇩 HACKDEEM OPOK TSEL
    url: 'http://hi.bonds.id/ping'
    interval: 300
    type: select
    proxies:
    - "🇸🇬 Singapore 1 HE"
    - "🇸🇬 Singapore 2 HE"
    - "🇸🇬 Singapore 1 CTB"
    - "🇸🇬 Singapore 2 CTB"
rules:
  - MATCH,🇮🇩 HACKDEEM OPOK TSEL
